name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: ./  # Change if your site is in a subfolder like `dist` or `build`
          production-branch: main
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
